spring:
  application:
    name: ${APPLICATION_NAME:wastemanager-service}
    zipkin: http://${ZIPKIN_HOST:host.docker.internal}:${ZIPKIN_PORT:9411}
  kafka:
    bootstrap-servers: http://${KAFKA_HOST:host.docker.internal}:${KAFKA_PORT:9092}
server:
  port: ${APPLICATION_PORT:${SERVER_PORT:0}}
  name: ${APPLICATION_NAME:gateway-service}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:host.docker.internal}:${EUREKA_PORT:8761}/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
zipkin:
  baseurl: http://${ZIPKIN_HOST:host.docker.internal}:${ZIPKIN_PORT:9411}
  sample:
    probability: 1.0